enableVersioning: true
handle: about
name: About
propagationMethod: all
siteSettings:
  9e92814a-721a-4b15-ad0e-5862784c6bd0:
    enabledByDefault: true
    hasUrls: true
    template: about
    uriFormat: about
type: single
