enableVersioning: true
handle: creative
name: Creative
propagationMethod: all
siteSettings:
  9e92814a-721a-4b15-ad0e-5862784c6bd0:
    enabledByDefault: true
    hasUrls: true
    template: creative/_entry
    uriFormat: 'creative/{slug}'
structure:
  maxLevels: null
  uid: b1f17bc3-af70-4623-8c24-3ae7208d0208
type: structure
