enableVersioning: true
handle: menu
name: Menu
propagationMethod: all
siteSettings:
  9e92814a-721a-4b15-ad0e-5862784c6bd0:
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 1d387e25-63dc-4d47-8019-596c0778bc14
type: structure
